Get NPS API module setup
technomooney/capstone_group_3_project_3 pull request #16
Opened 2023-03-12 02:12 UTC by oscar-chiqui

This code provides a way to collect park data from the National Park Service API using the Park class and the park_data_collection function.

- This code could benefit from modularization and unit testing.
- 
1: Separate the Park class and the park_data_collection function into their own modules,  park.py, and api.py, respectively.
2: Create a test module,  test_api.py, and test_api2.py  to test the API module's functions using the "unittest: module.
3: Use a mocking library like 'unittest.mock' to mock the National Park Service API response.

P.D: This code will continue to be modified since I only wanted to put into practice the knowledge and methods to use the API.

I need to know if my code or your code is compatible. I would also appreciate your feedback.

I did a lot of commits because I made errors in folders and the code that I didn't write well.

@technomooney @claraj @natalie-pratt @MCTCJulesO

2023-03-14 20:19 UTC, natalie-pratt requested changes
Already discussed but here it is in writing - better structure and easier to test if the request and data processing are in separate functions, in addition to importing the Park class to the api file in order for it to work. Thanks!

2023-03-15 18:06 UTC, technomooney commented
> Already discussed but here it is in writing - better structure and easier to test if the request and data processing are in separate functions, in addition to importing the Park class to the api file in order for it to work. Thanks!

i want to say that the park objects will be sent to the module as needed. so when the module is called should get a park object. so then the api does not need to have a copy of the park class. it just adds to an existing object.... or that is what i think. let me know what you think about that... you can look at what i did in the weather api for testing (not unit testing)

2023-03-15 18:07 UTC, technomooney commented on .gitignore
> +
why was this added? it should be in the rest of the git ignore file... as this git ignore file was made by GitHub.

2023-03-15 18:17 UTC, technomooney requested changes
this looks good... there are only a few things i would change...

2023-03-15 18:17 UTC, technomooney commented on README.md
this is not needed. if you will make a readme put it in the module folder not the main folder. when we are done this will be edited to reflect the project state and features

2023-03-15 18:17 UTC, technomooney commented on web_api/national_park/park.py
> +# he __repr__ method is a special method that returns a string representation of the object, which is useful for debugging and for generating informative error messages. In this case,
check spelling. i dont know what IDE you are using but you can use "streetsidesoftware.code-spell-checker" if you are using vs code.

2023-03-15 19:25 UTC, claraj commented on web_api/national_park/api.py
> +    api_key = os.getenv('NPS_API_KEY') # a GET request to the National Park Service API.
This comment doesn't match what the code does

2023-03-15 19:26 UTC, claraj commented on web_api/national_park/api.py
> +    response = requests.get(url, params=query)
Error handling needed - what if there's no connection to the server?

2023-03-15 19:27 UTC, claraj commented on web_api/national_park/api.py
> +    response_data = response.json()
Error handling - what if the response isn't JSON format?

2023-03-15 19:27 UTC, claraj commented on web_api/national_park/api.py
> +    return response_data.get("data", [])
Please explain why you chose an empty list as a default if there is no data

2023-03-15 19:28 UTC, claraj commented on web_api/national_park/national_park_service.py
Will this file be used?

2023-03-15 19:29 UTC, claraj commented on web_api/national_park/test_api.py
> +        self.assertIsNotNone(parks[0].full_name)
Instead of assertIsNotNone, it would be better to assert the data has the value you expect it to.

2023-03-16 22:05 UTC, technomooney commented on web_api/national_park/national_park_service.py
no. it was the template for testing i think.... or that is what i remember from the last meeting

2023-03-18 02:13 UTC, MCTCJulesO commented on web_api/national_park/national_park_service.py
Correct, Oscar said it can be deleted. He was just using that as a base for testing I think he said as well.

2023-03-19 20:57 UTC, technomooney requested changes
let us know if you need help with getting these changes done.

2023-03-19 20:57 UTC, technomooney commented on web_api/national_park/park.py
> +
please add 
```
self.forecast: dict = {}
```
so we dont need to have a separate park weather data class thanks!

2023-03-19 20:57 UTC, technomooney commented on web_api/national_park/api.py
> +    api_key = os.getenv('NPS_API_KEY') # a GET request to the National Park Service API.
we should move the API key to be a global variable. so when we start adding new functions that use different API end points we don't need to repeat this line

2023-03-22 19:09 UTC, natalie-pratt requested changes

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/test_api.py
> +        parks = park_data_collection("co", "canyon", None, 10)
Calls function "park_data_collection" from api.py that does not exist.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/test.api2.py
> +        parks_data_list = park_data_collection("MA", park_code="abcd", limit=1)
This test file also calls the nonexistent function "park_data_collection"

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/api.py
> +    query = {"api_key":api_key, "q": search_query, "stateCode": state, "limit": limit, "parkCode": park_code}
The 'q' here is supposed to be 'searchQuery'. When it's 'q' it returns {'total': '0', 'limit': '50', 'start': '0', 'data': []} and doesn't return data.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/national_parks.py
> +api_key = 'NPS_API_KEY'
This is going to need to be `os.environ.get('NPS_API_KEY')`, otherwise, it won't know to use the environment variable from the local PC. Currently, it's just setting the key value to 'NPS_API_KEY' itself.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/national_parks.py
> +        print('Error: ', e)
Maybe you already knew this and it was just for testing, but in the production version of this code this should return the error code/message or log it rather than print.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/national_parks.py
> +    if data is not None:
This doesn't work - the initializer for the Park class takes four arguments: full_name, description, park_code, and location. Here, we're getting an error because this line that creates the park object only has the first two necessary arguments. Either we need to create the park object with all four arguments in this function, or we could maybe change the initializer so that those values can be None on init and then added in later.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/national_parks.py
> +if __name__ == '__main__':
I'm assuming this is for testing - would want to get rid of these prints before merging to main.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/national_parks.py
> +        for park_data in data['data']:
I think that there should be an else clause here that does the error handling if there is no data. If there isn't data then it can return a message instead of doing it when the function is called.

2023-03-22 19:09 UTC, natalie-pratt commented on web_api/national_park/national_parks.py
> +    if data is not None:
I'm not sure exactly how it's been planned that we'll set up the Park objects. But either way, this is an error.

2023-03-26 19:39 UTC, MCTCJulesO requested changes
I am not sure about having user inputs and displaying them data here. I do not think this is how we intended this to work.

2023-03-26 20:14 UTC, technomooney commented
resolved a bunch of outdated comments

2023-03-26 20:16 UTC, technomooney commented
having @natalie-pratt push the code she worked on for the nps api. and we will request re-reviews.

2023-03-26 20:28 UTC, technomooney approved these changes
looks like it will work for the current needs... we are in crunch mode here so i didnt do all kinds of testing like i should have....

2023-03-26 20:34 UTC, MCTCJulesO approved these changes
@natalie-pratt this is more what I was looking for in the code.

2023-03-26 20:34 UTC, jk3132kv approved these changes

2023-03-26 20:36 UTC, MCTCJulesO approved these changes

2023-03-26 20:37 UTC, MCTCJulesO approved these changes

2023-03-26 20:38 UTC, jk3132kv approved these changes

2023-03-26 20:38 UTC, natalie-pratt approved these changes

2023-03-26 20:39 UTC, merged