Web api wiring
technomooney/capstone_group_3_project_3 pull request #24
Opened 2023-03-26 21:23 UTC by natalie-pratt

Not finished yet - so far only have the Unsplash function going. Let me know if this is what we're looking for!

2023-03-26 21:55 UTC, jk3132kv approved these changes

2023-03-27 00:32 UTC, MCTCJulesO approved these changes
This looks good so far!

2023-03-27 01:08 UTC, technomooney requested changes
Just a few changes from what i can see

2023-03-27 01:08 UTC, technomooney commented on web_api/national_park/national_parks.py
removed the redundant code to make it a little cleaner.

2023-03-27 01:08 UTC, technomooney commented on web_api/web_api_wiring.py
> +    if error:
we should put a return None there so it still returns something if there is an error.

2023-03-27 01:08 UTC, technomooney commented on web_api/web_api_wiring.py
> +        print(f'An error has occurred: {error}') # TODO - switch to log instead of print
return none here too

2023-03-27 01:35 UTC, natalie-pratt commented
@technomooney I made the changes

2023-03-28 16:14 UTC, technomooney approved these changes
ok looks good. if i find issues i will fix them in the ui_finalization branch.

2023-03-28 16:16 UTC, merged

2023-03-28 16:18 UTC, natalie-pratt commented
Completes issue #22